version: "3.9"

services:
  backend:
    build:
      context: ../Backend
    image: lab_seq_be:dev
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../Frontend
    image: lab_seq_fe
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
